-keep class io.ktor.client.engine.java.JavaHttpEngineContainer
-keep class kotlinx.coroutines.swing.SwingDispatcherFactory
-keep class com.arkivanov.decompose.extensions.compose.jetbrains.mainthread.SwingMainThreadChecker
-dontwarn org.slf4j.**
