FROM amazoncorretto:17 AS builder
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew server:shadowJar

FROM amazoncorretto:17 as runner

ARG POSTGRES_PORT
ARG POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_HOST
ARG HOST
ARG PORT
ARG REDIRECT_BASE_URL
ARG CORS_PORT
ARG CORS_HOST
ARG CORS_SCHEME

ENV POSTGRES_PORT=${POSTGRES_PORT}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_HOST=${POSTGRES_HOST}
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV REDIRECT_BASE_URL=${REDIRECT_BASE_URL}
ENV CORS_PORT=${CORS_PORT}
ENV CORS_HOST=${CORS_HOST}
ENV CORS_SCHEME=${CORS_SCHEME}

EXPOSE ${PORT}

COPY --from=builder ./server/build/libs/server-all.jar ./server.jar

ENTRYPOINT ["java", "-jar", "server.jar"]
